# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date_edited',
        ),
        migrations.RemoveField(
            model_name='news',
            name='edited_by',
        ),
        migrations.AddField(
            model_name='news',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_written',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='save as draft'),
        ),
        migrations.AlterField(
            model_name='player',
            name='db_profile',
            field=models.PositiveIntegerField(blank=True, help_text='Profile ID in players database', null=True, verbose_name='DB profile'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='suffix',
            field=models.CharField(blank=True, help_text="Suffix added to member's name, for example: >SrM<", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='value',
            field=models.IntegerField(help_text='Used for sorting; greater value -> rank displayed higher'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='value',
            field=models.IntegerField(default=0, help_text='Used for sorting; greater value -> higher on the list'),
        ),
    ]
