# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20171103_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='hints',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_sticky',
            field=models.BooleanField(default=False, verbose_name='pin at the top'),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Inactive servers aren't displayed"),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="If there are too many or too few servers marked as featured, 'value' will be the deciding factor", verbose_name='feature on front page'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
