# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20171110_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='verbose_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='setting'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='hints',
            field=models.TextField(blank=True, null=True),
        ),
    ]
