# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20171110_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.FilePathField(blank=True, match='.*\\.png', null=True, path='F:\\webdev\\myt/media//media/'),
        ),
    ]
